name: Run Python Tests

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
  pull_request:
    branches:
      - main # Or your default branch

jobs:
  test:
    name: Run tests with uv and pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Match the version used for publishing or use a matrix

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: 'latest'

      - name: Install dependencies
        run: uv sync --all-extras # Installs main and dev dependencies

      - name: Run tests
        run: uv run pytest
